# Sprint 3.2: Estructura d'una matriu

## Objectius
* Dimensions, formes
* Vectoritzacio, Broadcasting
* Index i mask
* Manipulació d'imatges amb Numpy

## Exercicis

### Exercici 1

**Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.**

In [1]:
import numpy as np

In [2]:
array = np.random.randint(500, size=8, dtype='int64')
array

array([ 53, 125, 188, 317, 157, 107, 235, 106])

In [3]:
array.ndim

1

In [4]:
print(array.shape)

(8,)


In [5]:
print(array.dtype)

int64


### Exercici 2

**De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.**

In [6]:
mean = np.mean(array)
mean

161.0

In [7]:
new_array = np.subtract(array, int(mean))
new_array

array([-108,  -36,   27,  156,   -4,  -54,   74,  -55])

### Exercici 3

**Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.**

In [8]:
#matrix = np.array([1, 2, 3, 4, 5], ndmin=5)

matrix = np.random.randint(1, 100, (5, 5))
print(matrix)
print('number of dimensions :', matrix.ndim)
print('shape of the matrix:', matrix.shape)

[[28 48  6 41 73]
 [ 6 71 64 99  3]
 [15 88 18 64 43]
 [45 75 84 32 55]
 [91 34 55 64  9]]
number of dimensions : 2
shape of the matrix: (5, 5)


In [9]:
print("Matrix max value: ", np.max(matrix))

Matrix max value:  99


In [10]:
for row in matrix:
    print("Row {0} max value: {1}".format(row, np.max(row)))

Row [28 48  6 41 73] max value: 73
Row [ 6 71 64 99  3] max value: 99
Row [15 88 18 64 43] max value: 88
Row [45 75 84 32 55] max value: 84
Row [91 34 55 64  9] max value: 91


### Exercici 4

**Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".**

In [11]:
matrix_a = np.random.randint(1, 100, (5, 5))
print(matrix_a)
print('number of dimensions :', matrix_a.ndim)
print('shape of the matrix:', matrix_a.shape)

[[ 8 53 15 92 11]
 [89 94 85 87 50]
 [ 6 34 43 29 86]
 [87 80 71 45 30]
 [82 95 18 37 70]]
number of dimensions : 2
shape of the matrix: (5, 5)


In [12]:
matrix_b = np.random.randint(1, 100, (5, 5))
print(matrix_b)
print('number of dimensions :', matrix_b.ndim)
print('shape of the matrix:', matrix_b.shape)

[[ 1 57 65 59 46]
 [87 83 61  9 94]
 [37  7 65 14 55]
 [37 97 15 74 95]
 [65 10 35  8 74]]
number of dimensions : 2
shape of the matrix: (5, 5)


In [13]:
matrix_a + matrix_b

array([[  9, 110,  80, 151,  57],
       [176, 177, 146,  96, 144],
       [ 43,  41, 108,  43, 141],
       [124, 177,  86, 119, 125],
       [147, 105,  53,  45, 144]])

In [14]:
matrix_c = np.random.randint(1, 100, (1))
print(matrix_c)
print('number of dimensions :', matrix_c.ndim)
print('shape of the matrix:', matrix_c.shape)
matrix_a + matrix_c

[50]
number of dimensions : 1
shape of the matrix: (1,)


array([[ 58, 103,  65, 142,  61],
       [139, 144, 135, 137, 100],
       [ 56,  84,  93,  79, 136],
       [137, 130, 121,  95,  80],
       [132, 145,  68,  87, 120]])

Exemple fent servir la classe **broadcast** de la llibreria **Numpy**:
https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html#numpy.broadcast

In [15]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [16]:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [17]:
%%script python --no-raise-error

import numpy as np

z = np.array([1.0, 2.0, 3.0, 4.0])
print(z)
print('number of dimensions of Z :', z.ndim)
print('shape of the Z matrix:', z.shape)

a = np.random.randint(1, 100, (3, 3))
print('\n',a)
print('number of dimensions of A :', a.ndim)
print('shape of the A matrix:', a.shape)

b = np.random.randint(1, 100, (5, 5))
print('\n', b)
print('number of dimensions of B :', b.ndim)
print('shape of the B matrix:', b.shape)

print('\n', a * b)
print('\n', a * z)

[1. 2. 3. 4.]
number of dimensions of Z : 1
shape of the Z matrix: (4,)

 [[ 4 95 82]
 [12 59 94]
 [60 65 40]]
number of dimensions of A : 2
shape of the A matrix: (3, 3)

 [[82 24 64 96 71]
 [63 56 37 70 61]
 [61 16 53 39  3]
 [48 91 43 11 88]
 [66 98 91 96 64]]
number of dimensions of B : 2
shape of the B matrix: (5, 5)


Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
ValueError: operands could not be broadcast together with shapes (3,3) (5,5) 


### Exercici 5
**Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.**

In [18]:
print(matrix)

val_2_3 = matrix[1][2]
print("\nRow 2 - colum 3 value: ", val_2_3)

val_4_4 = matrix[3][3]
print("\nRow 4 - colum 4 value: ", val_4_4)

print("\nSum values: ", val_2_3 + val_4_4)

[[28 48  6 41 73]
 [ 6 71 64 99  3]
 [15 88 18 64 43]
 [45 75 84 32 55]
 [91 34 55 64  9]]

Row 2 - colum 3 value:  64

Row 4 - colum 4 value:  32

Sum values:  96


### Exercici 6

**Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre. Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.**

In [19]:
print("Original matrix:\n\n", matrix)

masked_matrix = (matrix % 4 == 0)
print("\n\nMasked matrix:\n\n", masked_matrix)

masked_matrix = masked_matrix.astype(np.int)
masked_matrix

Original matrix:

 [[28 48  6 41 73]
 [ 6 71 64 99  3]
 [15 88 18 64 43]
 [45 75 84 32 55]
 [91 34 55 64  9]]


Masked matrix:

 [[ True  True False False False]
 [False False  True False False]
 [False  True False  True False]
 [False False  True  True False]
 [False False False  True False]]


array([[1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0]])

### Exercici 7

**A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.**

In [20]:
indexed_array = matrix * masked_matrix
indexed_array

array([[28, 48,  0,  0,  0],
       [ 0,  0, 64,  0,  0],
       [ 0, 88,  0, 64,  0],
       [ 0,  0, 84, 32,  0],
       [ 0,  0,  0, 64,  0]])

### Exercici 8

**Manipulació d'imatges amb matplotlib**

Carregareu qualsevol imatge (jpg, png ..) amb Matplotlib. Adoneu-vos que les imatges RGB (Red, Green, Blue) són realment només amplades × alçades × 3 matrius (tres canals Vermell, Verd i Blau), una per cada color de nombres enters int8.

Ajuda: Importeu, ```import matplotlib.image as mpimg```. Estudieu el mètode ```mpimg.imread()```

![Carnaval Image](img/carnaval.jpg)

In [21]:
import matplotlib.image as mpimg

img = mpimg.imread('img/carnaval.jpg', format='jpg')
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 55  50  72]
  [ 43  38  60]
  [ 36  28  49]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 62  54  77]
  [ 49  41  64]
  [ 40  32  53]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 69  61  85]
  [ 57  49  72]
  [ 46  38  61]]

 ...

 [[ 21  34  25]
  [ 21  34  25]
  [ 21  34  25]
  ...
  [190   4  27]
  [190   4  27]
  [186   0  23]]

 [[ 23  36  27]
  [ 23  36  27]
  [ 23  36  27]
  ...
  [190   4  27]
  [190   4  27]
  [186   0  23]]

 [[ 23  36  27]
  [ 23  36  27]
  [ 23  36  27]
  ...
  [190   4  27]
  [190   4  27]
  [186   0  23]]]


**Manipuleu aquests bytes i torneu a utilitzar Matplotlib per desar la imatge modificada un cop hàgiu acabat.**

**Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.**

**Utilitzar el mètode, mpimg.imsave() de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.**

In [22]:
no_green_img = img * [1, 0, 1]
no_green_img

array([[[255,   0, 255],
        [255,   0, 255],
        [255,   0, 255],
        ...,
        [ 55,   0,  72],
        [ 43,   0,  60],
        [ 36,   0,  49]],

       [[255,   0, 255],
        [255,   0, 255],
        [255,   0, 255],
        ...,
        [ 62,   0,  77],
        [ 49,   0,  64],
        [ 40,   0,  53]],

       [[255,   0, 255],
        [255,   0, 255],
        [255,   0, 255],
        ...,
        [ 69,   0,  85],
        [ 57,   0,  72],
        [ 46,   0,  61]],

       ...,

       [[ 21,   0,  25],
        [ 21,   0,  25],
        [ 21,   0,  25],
        ...,
        [190,   0,  27],
        [190,   0,  27],
        [186,   0,  23]],

       [[ 23,   0,  27],
        [ 23,   0,  27],
        [ 23,   0,  27],
        ...,
        [190,   0,  27],
        [190,   0,  27],
        [186,   0,  23]],

       [[ 23,   0,  27],
        [ 23,   0,  27],
        [ 23,   0,  27],
        ...,
        [190,   0,  27],
        [190,   0,  27],
        [186,   0,  23]]

In [23]:
mpimg.imsave("img/no_green_img.jpg", no_green_img.astype(np.uint8), format="jpg")

![Modified Image](img/no_green_img.jpg)

In [24]:
no_blue_img = img * [1, 1, 0]
no_blue_img

array([[[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [ 55,  50,   0],
        [ 43,  38,   0],
        [ 36,  28,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [ 62,  54,   0],
        [ 49,  41,   0],
        [ 40,  32,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [ 69,  61,   0],
        [ 57,  49,   0],
        [ 46,  38,   0]],

       ...,

       [[ 21,  34,   0],
        [ 21,  34,   0],
        [ 21,  34,   0],
        ...,
        [190,   4,   0],
        [190,   4,   0],
        [186,   0,   0]],

       [[ 23,  36,   0],
        [ 23,  36,   0],
        [ 23,  36,   0],
        ...,
        [190,   4,   0],
        [190,   4,   0],
        [186,   0,   0]],

       [[ 23,  36,   0],
        [ 23,  36,   0],
        [ 23,  36,   0],
        ...,
        [190,   4,   0],
        [190,   4,   0],
        [186,   0,   0]]

In [25]:
mpimg.imsave("img/no_blue_img.jpg", no_blue_img.astype(np.uint8), format="jpg")

![Modified Image](img/no_blue_img.jpg)

## Resources

* https://www.w3schools.com/python/numpy/numpy_intro.asp
* https://numpy.org/doc/stable/user/basics.broadcasting.html
* https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html#numpy.broadcast
* https://numpy.org/doc/stable/reference/routines.array-manipulation.html
* https://numpy.org/doc/stable/reference/maskedarray.generic.html
* https://www.python-course.eu/numpy_masking.php
* https://matplotlib.org/stable/tutorials/introductory/images.html
* https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imsave.html#matplotlib.pyplot.imsave