# Sprint 3.2: Estructura d'una matriu

## Objectius
* Dimensions, formes
* Vectoritzacio, Broadcasting
* Index i mask
* Manipulació d'imatges amb Numpy

## Exercicis

### Exercici 1

**Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.**

In [1]:
import numpy as np

In [2]:
array = np.random.randint(500, size=8, dtype='int64')
array

array([182, 211, 224, 155, 417, 208, 374, 337])

In [3]:
array.ndim

1

In [4]:
print(array.shape)

(8,)


In [5]:
print(array.dtype)

int64


### Exercici 2

**De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.**

In [6]:
mean = np.mean(array)
mean

263.5

In [7]:
new_array = np.subtract(array, int(mean))
new_array

array([ -81,  -52,  -39, -108,  154,  -55,  111,   74])

### Exercici 3

**Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.**

In [8]:
#matrix = np.array([1, 2, 3, 4, 5], ndmin=5)

matrix = np.random.randint(1, 100, (5, 5))
print(matrix)
print('number of dimensions :', matrix.ndim)
print('shape of the matrix:', matrix.shape)

[[53 60 47 40 43]
 [38 95 73 88 96]
 [41 61 64 28 85]
 [71 47 33 19  4]
 [54 56 72 55 40]]
number of dimensions : 2
shape of the matrix: (5, 5)


In [9]:
print("Matrix max value: ", np.max(matrix))

Matrix max value:  96


In [10]:
for row in matrix:
    print("Row {0} max value: {1}".format(row, np.max(row)))

Row [53 60 47 40 43] max value: 60
Row [38 95 73 88 96] max value: 96
Row [41 61 64 28 85] max value: 85
Row [71 47 33 19  4] max value: 71
Row [54 56 72 55 40] max value: 72


### Exercici 4

**Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".**

In [11]:
matrix_a = np.random.randint(1, 100, (5, 5))
print(matrix_a)
print('number of dimensions :', matrix_a.ndim)
print('shape of the matrix:', matrix_a.shape)

[[46 75 33 47 13]
 [40 14 42 80 95]
 [16 20 61 42 23]
 [89 78 86  8 75]
 [10 27 24 98 47]]
number of dimensions : 2
shape of the matrix: (5, 5)


In [12]:
matrix_b = np.random.randint(1, 100, (5, 5))
print(matrix_b)
print('number of dimensions :', matrix_b.ndim)
print('shape of the matrix:', matrix_b.shape)

[[67 60 76 35 59]
 [ 6 91 53 57 23]
 [66 28 38 97 62]
 [70 25 28 42 33]
 [ 1 94 26 43 14]]
number of dimensions : 2
shape of the matrix: (5, 5)


In [13]:
matrix_a + matrix_b

array([[113, 135, 109,  82,  72],
       [ 46, 105,  95, 137, 118],
       [ 82,  48,  99, 139,  85],
       [159, 103, 114,  50, 108],
       [ 11, 121,  50, 141,  61]])

In [14]:
matrix_c = np.random.randint(1, 100, (1))
print(matrix_c)
print('number of dimensions :', matrix_c.ndim)
print('shape of the matrix:', matrix_c.shape)
matrix_a + matrix_c

[54]
number of dimensions : 1
shape of the matrix: (1,)


array([[100, 129,  87, 101,  67],
       [ 94,  68,  96, 134, 149],
       [ 70,  74, 115,  96,  77],
       [143, 132, 140,  62, 129],
       [ 64,  81,  78, 152, 101]])

Exemple fent servir la classe **broadcast** de la llibreria **Numpy**:

In [15]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [16]:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### Exercici 5
**Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.**

In [17]:
print(matrix)

val_2_3 = matrix[1][2]
print("\nRow 2 - colum 3 value: ", val_2_3)

val_4_4 = matrix[3][3]
print("\nRow 4 - colum 4 value: ", val_4_4)

print("\nSum values: ", val_2_3 + val_4_4)

[[53 60 47 40 43]
 [38 95 73 88 96]
 [41 61 64 28 85]
 [71 47 33 19  4]
 [54 56 72 55 40]]

Row 2 - colum 3 value:  73

Row 4 - colum 4 value:  19

Sum values:  92


### Exercici 6

**Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre. Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.**

In [18]:
print("Original matrix:\n\n", matrix)

masked_matrix = (matrix % 4 == 0)
print("\n\nMasked matrix:\n\n", masked_matrix)

masked_matrix = masked_matrix.astype(np.int)
masked_matrix

Original matrix:

 [[53 60 47 40 43]
 [38 95 73 88 96]
 [41 61 64 28 85]
 [71 47 33 19  4]
 [54 56 72 55 40]]


Masked matrix:

 [[False  True False  True False]
 [False False False  True  True]
 [False False  True  True False]
 [False False False False  True]
 [False  True  True False  True]]


array([[0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 1, 0, 1]])

### Exercici 7

**A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.**

In [19]:
indexed_array = matrix * masked_matrix
indexed_array

array([[ 0, 60,  0, 40,  0],
       [ 0,  0,  0, 88, 96],
       [ 0,  0, 64, 28,  0],
       [ 0,  0,  0,  0,  4],
       [ 0, 56, 72,  0, 40]])

### Exercici 8

**Manipulació d'imatges amb matplotlib**

Carregareu qualsevol imatge (jpg, png ..) amb Matplotlib. Adoneu-vos que les imatges RGB (Red, Green, Blue) són realment només amplades × alçades × 3 matrius (tres canals Vermell, Verd i Blau), una per cada color de nombres enters int8.

Ajuda: Importeu, ```import matplotlib.image as mpimg```. Estudieu el mètode ```mpimg.imread()```

![Carnaval Image](img/carnaval.jpg)

In [20]:
import matplotlib.image as mpimg

img = mpimg.imread('img/carnaval.jpg', format='jpg')
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 55  50  72]
  [ 43  38  60]
  [ 36  28  49]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 62  54  77]
  [ 49  41  64]
  [ 40  32  53]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [ 69  61  85]
  [ 57  49  72]
  [ 46  38  61]]

 ...

 [[ 21  34  25]
  [ 21  34  25]
  [ 21  34  25]
  ...
  [190   4  27]
  [190   4  27]
  [186   0  23]]

 [[ 23  36  27]
  [ 23  36  27]
  [ 23  36  27]
  ...
  [190   4  27]
  [190   4  27]
  [186   0  23]]

 [[ 23  36  27]
  [ 23  36  27]
  [ 23  36  27]
  ...
  [190   4  27]
  [190   4  27]
  [186   0  23]]]


**Manipuleu aquests bytes i torneu a utilitzar Matplotlib per desar la imatge modificada un cop hàgiu acabat.**

**Mostreu-me a veure què passa quan eliminem el canal G Verd o B Blau. Hauries d'utilitzar la indexació per seleccionar el canal que voleu anul·lar.**

**Utilitzar el mètode, mpimg.imsave() de la llibreria importada, per guardar les imatges modificades i que haureu de pujar al vostre repositori a github.**

In [21]:
no_green_img = img * [1, 0, 1]
no_green_img

array([[[255,   0, 255],
        [255,   0, 255],
        [255,   0, 255],
        ...,
        [ 55,   0,  72],
        [ 43,   0,  60],
        [ 36,   0,  49]],

       [[255,   0, 255],
        [255,   0, 255],
        [255,   0, 255],
        ...,
        [ 62,   0,  77],
        [ 49,   0,  64],
        [ 40,   0,  53]],

       [[255,   0, 255],
        [255,   0, 255],
        [255,   0, 255],
        ...,
        [ 69,   0,  85],
        [ 57,   0,  72],
        [ 46,   0,  61]],

       ...,

       [[ 21,   0,  25],
        [ 21,   0,  25],
        [ 21,   0,  25],
        ...,
        [190,   0,  27],
        [190,   0,  27],
        [186,   0,  23]],

       [[ 23,   0,  27],
        [ 23,   0,  27],
        [ 23,   0,  27],
        ...,
        [190,   0,  27],
        [190,   0,  27],
        [186,   0,  23]],

       [[ 23,   0,  27],
        [ 23,   0,  27],
        [ 23,   0,  27],
        ...,
        [190,   0,  27],
        [190,   0,  27],
        [186,   0,  23]]

In [22]:
mpimg.imsave("img/no_green_img.jpg", no_green_img.astype(np.uint8), format="jpg")

![Modified Image](img/no_green_img.jpg)

In [23]:
no_blue_img = img * [1, 1, 0]
no_blue_img

array([[[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [ 55,  50,   0],
        [ 43,  38,   0],
        [ 36,  28,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [ 62,  54,   0],
        [ 49,  41,   0],
        [ 40,  32,   0]],

       [[255, 255,   0],
        [255, 255,   0],
        [255, 255,   0],
        ...,
        [ 69,  61,   0],
        [ 57,  49,   0],
        [ 46,  38,   0]],

       ...,

       [[ 21,  34,   0],
        [ 21,  34,   0],
        [ 21,  34,   0],
        ...,
        [190,   4,   0],
        [190,   4,   0],
        [186,   0,   0]],

       [[ 23,  36,   0],
        [ 23,  36,   0],
        [ 23,  36,   0],
        ...,
        [190,   4,   0],
        [190,   4,   0],
        [186,   0,   0]],

       [[ 23,  36,   0],
        [ 23,  36,   0],
        [ 23,  36,   0],
        ...,
        [190,   4,   0],
        [190,   4,   0],
        [186,   0,   0]]

In [24]:
mpimg.imsave("img/no_blue_img.jpg", no_blue_img.astype(np.uint8), format="jpg")

![Modified Image](img/no_blue_img.jpg)

## Resources

* https://www.w3schools.com/python/numpy/numpy_intro.asp
* https://numpy.org/doc/stable/user/basics.broadcasting.html
* https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html#numpy.broadcast
* https://numpy.org/doc/stable/reference/routines.array-manipulation.html
* https://numpy.org/doc/stable/reference/maskedarray.generic.html
* https://www.python-course.eu/numpy_masking.php
* https://matplotlib.org/stable/tutorials/introductory/images.html
* https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imsave.html#matplotlib.pyplot.imsave